# Generated by Django 5.1.2 on 2024-10-22 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucketlist', '0002_bucketlist_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BucketListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('travel', 'Travel'), ('career', 'Career'), ('personal', 'Personal')], default='personal', max_length=50)),
                ('priority', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=50)),
                ('bucketlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bucketlist.bucketlist')),
            ],
        ),
    ]
